spring:
  application:
    name: otel-dummy

otel:
  service:
    name: my-spring-service

  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}

  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: otlp